baseURL = 'https://brams153.github.io/BETO_Legal_Mexico/'
canonifyURLs = true
relativeURLs = false
locale = 'es-mx'
title = 'BETO Legal México'
theme = 'book'

[params]
  BookSection = 'docs'
  BookTheme = 'light'

# Mapeo correcto de carpetas en Hugo Moderno
[module]
  [[module.mounts]]
    source = "static"
    target = "static"
