baseURL = 'https://brams153.github.io/BETO_Legal_Mexico/'
# Intenta con esto si lo anterior no funciona
canonifyURLs = false 
relativeURLs = false
languageCode = 'es-mx'
title = 'BETO Legal México'
theme = 'book'
[params]
# Configuración básica para el tema Book
BookSection = 'docs'
BookTheme = 'light' # o 'dark'
