name: GitHub Pages con Hugo

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true # Esencial si tu tema de Hugo está como submódulo Git

      - name: Instalar Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.161.1'
          extended: true

      - name: Construir el sitio
        # YA NO USAMOS 'cd docs/hugo', compilamos directo desde la raíz
        run: hugo --minify

      - name: Subir artefacto para Pages
        uses: actions/upload-pages-artifact@v3
        with:
          # Al compilar desde la raíz, Hugo genera la carpeta 'public' en la raíz
          path: 'public'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Desplegar
        id: deployment
        uses: actions/deploy-pages@v4
